/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Subset/split a font.
 *
 * `input` is a protobuf-encoded `InputTemplate` — the exact bytes the existing C-FFI / WASM
 * entrypoints already accept, so the JS side can keep using its current proto encoder.
 *
 * Returns every streamed `EventMessage` as a protobuf-encoded `Buffer`, in emission order.
 * The final messages carry the chunked font data + the generated CSS; the JS side decodes
 * them with the same proto definitions it uses today.
 */
export declare function fontSplit(input: Buffer): Array<Buffer>
